name: Merge Test CI

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    environment: DEPLOYMENT_SECRET
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Configure Git to Use the PAT Token
        run: git config --global url."https://oauth2:${{ secrets.GH_PAT }}@github.com".insteadOf https://github.com
      - name: Clone Rust Source Repo
        run: |
          cd ..
          git clone https://github.com/${{ secrets.RS_SRC_GEN }} gen-src
          rsync -av ./printmedi-yaml-source/ ./gen-src/Formulas/

      - name: Run Test
        run: |
          cd ..
          cd gen-src && cargo test